_target_: src.models.retriever_moco_model.Retriever

lr: 5e-05
weight_decay: 0.0005
num_negatives: 241728 #167296+12544-64
encoder_momentum: 0.999
softmax_temperature: 0.5
batch_size: 64
num_workers: 4
max_epochs: 20
warmup_ratio: 0.1
