_target_: pytorch_lightning.Trainer

# set `1` to train on GPU, `0` to train on CPU only
gpus: 1

min_epochs: 1
max_epochs: 40
weights_summary: null
progress_bar_refresh_rate: 10
precision: 16
# val_check_interval: 1
auto_lr_find: True
# auto_scale_batch_size: True
move_metrics_to_cpu: True 
reload_dataloaders_every_epoch: True
# resume_from_checkpoint: "/opt/ml/code/pytorch_lightning_examples/3_RETRIEVER/logs/runs/2021-05-17/21-01-19/checkpoints/last.ckpt"
accumulate_grad_batches: 3
# amp_backend: 'apex'
# amp_level: 'O2'
# log_gpu_memory: 'min_max'

