_target_: pytorch_lightning.Trainer

# set `1` to train on GPU, `0` to train on CPU only
gpus: 1

min_epochs: 1
max_epochs: 30
weights_summary: null
progress_bar_refresh_rate: 10
precision: 16
# auto_scale_batch_size: True
# val_check_interval: 2
# val_check_interval: 0.1
auto_scale_batch_size: True
move_metrics_to_cpu: False
auto_lr_find: True
reload_dataloaders_every_epoch: True
# resume_from_checkpoint: "/opt/ml/code/pytorch_lightning_examples/5_RAG/logs/runs/2021-05-13/01-36-34/checkpoints/epoch=00.ckpt"
# amp_backend: 'apex'
# amp_level: 'O2'
# log_gpu_memory: 'min_max'
# resume_from_checkpoint: null
